import mongoose from 'mongoose'

const roundSchema = new mongoose.Schema({
  approach: { type: Object, required: false },
  fairways: { type: Object, required: false },
  greens: { type: Object, required: false },
  nonGhinRounds: { type: Object, required: false },
  putting: { type: Object, required: false },
  roundInfo: { type: Object, required: false },
  scoring: { type: Object, required: false },
  // sequence: { type: Number, required: false },
  // key: { type: String, required: false },
  // course: { type: String, required: false },
  // courseKey: { type: String, required: false },
  // date: { type: String, required: false },
  // formattedDate: { type: String, required: false },
  // scrambleRound: { type: Boolean, required: false },
  // leagueRound: { type: Boolean, required: false },
  // legacyRound: { type: Boolean, required: false },
  // boozeRound: { type: Boolean, required: false },
  // numHoles: { type: Number, required: false },
  // f9Putts: { type: Number, required: false },
  // b9Putts: { type: Number, required: false },
  // putts: { type: Number, required: false },
  // num3Putts: { type: Number, required: false },
  // f9PuttTotal: { type: Number, required: false },
  // b9PuttTotal: { type: Number, required: false },
  // out: { type: Number, required: false },
  // in: { type: Number, required: false },
  // total: { type: Number, required: false },
  // dtgF9Total: { type: Number, required: false },
  // dthF9Total: { type: Number, required: false },
  // fpmF9Total: { type: Number, required: false },
  // dtgB9Total: { type: Number, required: false },
  // dthB9Total: { type: Number, required: false },
  // fpmB9Total: { type: Number, required: false },
  // dtgTotal: { type: Number, required: false },
  // dthTotal: { type: Number, required: false },
  // fpmTotal: { type: Number, required: false },
  // dtgF9Average: { type: String, required: false },
  // dtgB9Average: { type: String, required: false },
  // dtgTotalAverage: { type: mongoose.Schema.Types.Mixed, required: false },
  // dthF9Average: { type: String, required: false },
  // dthB9Average: { type: String, required: false },
  // dthTotalAverage: { type: mongoose.Schema.Types.Mixed, required: false },
  // fpmF9Average: { type: String, required: false },
  // fpmB9Average: { type: String, required: false },
  // fpmTotalAverage: { type: mongoose.Schema.Types.Mixed, required: false },
  // numEagles: { type: Number, required: false },
  // numBirdies: { type: Number, required: false },
  // numPars: { type: Number, required: false },
  // numBogey: { type: Number, required: false },
  // numBogeyPlus: { type: Number, required: false },
  // coursePar: { type: Number, required: false },
  // scoreToPar: { type: Number, required: false },
  hole1: { type: Object, required: false },
  hole2: { type: Object, required: false },
  hole3: { type: Object, required: false },
  hole4: { type: Object, required: false },
  hole5: { type: Object, required: false },
  hole6: { type: Object, required: false },
  hole7: { type: Object, required: false },
  hole8: { type: Object, required: false },
  hole9: { type: Object, required: false },
  hole10: { type: Object, required: false },
  hole11: { type: Object, required: false },
  hole12: { type: Object, required: false },
  hole13: { type: Object, required: false },
  hole14: { type: Object, required: false },
  hole15: { type: Object, required: false },
  hole16: { type: Object, required: false },
  hole17: { type: Object, required: false },
  hole18: { type: Object, required: false }
  // fullFront9: { type: Boolean, required: false },
  // fullBack9: { type: Boolean, required: false },
  // partialFront9: { type: Boolean, required: false },
  // partialBack9: { type: Boolean, required: false },
  // fairways: {
  //   l: { type: Number, required: false },
  //   r: { type: Number, required: false },
  //   f: { type: Number, required: false },
  //   x: { type: Number, required: false },
  //   na: { type: Number, required: false },
  //   f9: { type: Number, required: false },
  //   b9: { type: Number, required: false }
  // },
  // greens: {
  //   g: { type: Number, required: false },
  //   x: { type: Number, required: false },
  //   gur: { type: Number, required: false },
  //   f9: { type: Number, required: false },
  //   b9: { type: Number, required: false }
  // },
  // puttLengthTotal: {type: Number, required: false },
  // puttLengthF9: {type: Number, required: false },
  // puttLengthB9: {type: Number, required: false },
  // dthF9: {type: Number, required: false },
  // dthB9: {type: Number, required: false },
  // dtgF9: {type: Number, required: false },
  // dtgB9: {type: Number, required: false }
}, { minimize: false, versionKey: false });

export default mongoose.model('golfrounds', roundSchema);